# ▄▄▄▄▄▄▄ ▄▄▄▄▄▄▄ ▄▄▄▄▄▄  ▄     ▄ ▄▄▄▄▄▄ ▄▄▄▄▄▄   ▄▄▄▄▄▄▄
#█  ▄    █       █      ██ █ ▄ █ █      █   ▄  █ █       █
#█ █▄█   █    ▄▄▄█  ▄    █ ██ ██ █  ▄   █  █ █ █ █  ▄▄▄▄▄█
#█       █   █▄▄▄█ █ █   █       █ █▄█  █   █▄▄█▄█ █▄▄▄▄▄
#█  ▄   ██    ▄▄▄█ █▄█   █       █      █    ▄▄  █▄▄▄▄▄  █
#█ █▄█   █   █▄▄▄█       █   ▄   █  ▄   █   █  █ █▄▄▄▄▄█ █
#█▄▄▄▄▄▄▄█▄▄▄▄▄▄▄█▄▄▄▄▄▄██▄▄█ █▄▄█▄█ █▄▄█▄▄▄█  █▄█▄▄▄▄▄▄▄█
#
# Plugin made by TheViperShow - 
settings:
  server-name: "Server"
  server-domain: "server.net"
  database:
    username: "user" # set your username
    password: "password" # set your password
    address: "127.0.0.1"
    port: 3306
    db-name: "bedwars" #set your DB name
  lobby:
    world-name: "world"
  attempt-load:
    - "solo"
    - "duo"
    - "quad"

